### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by dee-y** [ReubenTanYuErn/OpenSource-ChromeExtension---SimpleNotepad#1]
Hello @ReubenTanYuErn @yihwei95 @triplekkoh, i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by ReubenTanYuErn** [comment]
Greetings @dee-y ! Apologies for the delayed reply. I am honoured upon your interest and generosity on our project but we do have another team member working on the logo of this school project. 
Once again, thank you and have a good day.

**Comment by dee-y** [comment]
Alright no problem, thanks for the time.
